### ISSUE TITLE
Feature Request:  Add option to adjust delay from commandline

### ISSUE THREAD

**Issue by enxoco** [schollz/websitechanges#3]
Greetings,

I stumbled on this repo when trying to figure out a way to make my job (and the life of my PM) a little easier by automatically finding issues with sites we work on.  I love the simplicity and out of the box it has most of what I need.  I did have 2 simple requests. 

1) Add the ability to pass a delay flag on the command line instead of having it hardcoded in main.go.
2) Have a way to customize the folder name for images to make it easier to recognize.  

Already created a PR for this here: https://github.com/schollz/websitechanges/pull/2

**Comment by schollz** [comment]
Thanks @enxoco ! I'm glad it made things a little easier and I'm so happy that you made a PR with your upgrades :)
